config/routes.rb
Rails.application.routes.draw do
#  get 'members/new'
#  get 'members/create'

  root to: "posts#index" 
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :members do
    member do
      get "/show_members_posts", to: "members#show_member_posts"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :posts

  validates :first_name,  presence: true 
  validates :last_name,   presence: true
  validates :email,       presence: true
  validates :email, format: { with: /(\A([a-z]*\s*)*\<*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\>*\Z)/i }

  attachment :avatar
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:first_name, :last_name, :account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/posts
  def show_member_posts
    member = Member.find(params[:id])
    @member_posts = member.posts
    ap @member_posts
  end 

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # member /members
  # member /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :mobile_phone, :username, :avatar)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: @member, local: true) do |form| %>
<%= form.attachment_field :avatar %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</br>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :post_username %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :post_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :post_last_name %>
  </div>
  
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :post_email %>
  </div>

  <div class="field">
    <%= form.label :mobile_phone %>
    <%= form.text_field :mobile_phone, id: :post_mobile_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member details</h1>

<%= render 'form', post: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Members</h1>

<% @members.each do |member| %>
      <% if member.avatar.nil? %>
        <p>
          <%= member.first_name.capitalize %> has no avatar image 
        </p> <br>
      <% else %>
        <p> 
          <%= image_tag attachment_url(member, :avatar, :fill, 150, 150, format: "jpg") %>
        </p> </br>
      <% end %> 

      <p> 
        Name :      <%= member.first_name.capitalize %> 
                    <%= member.last_name.capitalize %> </br>
        Username:   <%= member.username %> </br>
        Email:      <%= member.email %> </br>
        Mobile No.: <%= member.mobile_phone %> 
      </p>
    
      <p>
      <%= link_to 'Show Member', member %> | 
      <%= link_to 'Edit', edit_member_path(member) %> <br>
     
      <%= link_to "Create New Post", new_post_path %> <br>
      <%= link_to "Destroy #{member.first_name.capitalize}", member, method: :delete, data: { confirm: 'Are you sure?' } %> </br>
       ---------------------------------------- </p>
    <% end %>
  

<br>

<%= link_to 'Add member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

    <% if @member.avatar.nil? %>
          <p> <%= @member.first_name.capitalize %> has no avatar image </p>
        <br>
          <% else %>
            <p><%= image_tag attachment_url(@member, :avatar, :fill, 150, 150, format: "jpg") %>
            </p>
          <% end %>
  <table>
    <tbody>
      </br>
        <td>  
            <strong>Member: </strong>
            <%= @member.first_name.capitalize %> 
            <%= @member.last_name.capitalize %>
        </td> 
      </br>
        <td>  
          <strong>Username: </strong>
            <%= @member.username %>
        </td> 
      </br>
        <td>  
          <strong>Email: </strong>
            <%= @member.email %>
        </td> 
      </br>
        <td>
          <strong>Mobile No.: </strong>
            <%= @member.mobile_phone %>
        </td> 
      </br>
    </tbody>
  </table>
<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %> |
<%= link_to "Create New Post for #{@member.first_name.capitalize}", new_post_path %>

app/views/members/show_member_posts.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

    <% @member_posts.each do |post| %>
     
      <p> Posted by <%= post.member.first_name %> </p>
      <% if post.profile_image.nil? %>
         <%= "No Image." %> </br>
      <% else %>
        <%= image_tag attachment_url(post, :profile_image, :fill, 400, 400) %> </br>
      <% end %>
        
      <h4> Caption: <%= post.caption %> </h4>
      
      <p>
        <%= link_to 'Show', post %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm:  'Are you sure?' } %> </br>
        ----------------------------------------
      </p>
      
    <% end %>
  